enviroment: test

server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: POC - Junit Tests
  profiles:
    active:  ${enviroment}

config:
  activate:
    on-profile: ${enviroment}
